[wechat]
cache_patterns = ["\\(\\d+\\)\\.[a-zA-Z0-9]+$", "-\\d{13}\\."]

[cleaning]
default_mode = "smart"
preserve_originals = true
min_file_size = 2048      # 2KB

[ui]
theme.primary_color = "blue"
theme.secondary_color = "green"
theme.highlight_color = "yellow"

[ui.keybindings]
quit = 'q'
up = 'k'
down = 'j'
left = 'h'
right = 'l'
delete = 'd'
